version: '3.6'

services:
  web:
    build: .
    volumes:
      - ./:/app
    working_dir: /app
    command: puma
    ports:
      - 3000:3000
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://postgres@db
    stdin_open: true
    tty: true

  db:
    image: postgres:10.3-alpine
    ports:
      - 5555:5432
